# Generated by Django 3.0.2 on 2020-04-07 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laticreteapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('details', models.CharField(max_length=10000, null=True)),
                ('categoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laticreteapp.lineCategory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solutionName', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('details', models.CharField(max_length=10000, null=True)),
                ('categoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laticreteapp.solutionCategory')),
            ],
            options={
                'verbose_name': 'Solution',
                'verbose_name_plural': 'Solutions',
            },
        ),
        migrations.RemoveField(
            model_name='solutiond',
            name='categoryName',
        ),
        migrations.DeleteModel(
            name='productD',
        ),
        migrations.DeleteModel(
            name='solutionD',
        ),
    ]
