# Generated by Django 3.0.2 on 2020-07-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laticreteapp', '0002_auto_20200407_0346'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('content', models.TextField(max_length=10000, null=True)),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='pdfFile',
            field=models.FileField(null=True, upload_to='static/'),
        ),
        migrations.AddField(
            model_name='product',
            name='videoFile',
            field=models.FileField(null=True, upload_to='static/'),
        ),
        migrations.AddField(
            model_name='solution',
            name='pdfFile',
            field=models.FileField(null=True, upload_to='static/'),
        ),
        migrations.AddField(
            model_name='solution',
            name='videoFile',
            field=models.FileField(null=True, upload_to='static/'),
        ),
    ]
