# Generated by Django 3.0.2 on 2020-08-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laticreteapp', '0006_auto_20200715_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='message',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='pastprojects',
            name='details',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
